In [15]:
import pandas as pd 

In [16]:
# قراءة البيانات
df = pd.read_csv("spam.csv")  # تأكد من استخدام اسم الملف الصحيح

# عرض أول خمس صفوف
print(df.head()) 

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...


In [17]:

# إضافة عمود spam بناءً على قيم Category
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [18]:
# حذف عمود Category إذا كان غير موجود
dataset = df.drop(['Category'], axis='columns', errors='ignore')
dataset

Message  spam
0     Go until jurong point, crazy.. Available only ...     0
1                         Ok lar... Joking wif u oni...     0
2     Free entry in 2 a wkly comp to win FA Cup fina...     1
3     U dun say so early hor... U c already then say...     0
4     Nah I don't think he goes to usf, he lives aro...     0
...                                                 ...   ...
5567  This is the 2nd time we have tried 2 contact u...     1
5568               Will ü b going to esplanade fr home?     0
5569  Pity, * was in mood for that. So...any other s...     0
5570  The guy did some bitching but I acted like i'd...     0
5571                         Rofl. Its true to its name     0

[5572 rows x 2 columns]

In [19]:
# إحصائيات جماعية
print(df.groupby('spam').describe()) 


     Category                    Message         \
        count unique   top  freq   count unique   
spam                                              
0        4825      1   ham  4825    4825   4516   
1         747      1  spam   747     747    641   

                                                              
                                                    top freq  
spam                                                          
0                                Sorry, I'll call later   30  
1     Please call our customer service representativ...    4  


In [20]:
from sklearn.model_selection import train_test_split

# تقسيم البيانات إلى تدريب واختبار
train, test = train_test_split(dataset, test_size=0.2, random_state=42)

# عرض شكل بيانات التدريب
print(train.shape) 


(4457, 2)


In [21]:


from sklearn.feature_extraction.text import CountVectorizer


In [22]:
# تحويل النصوص إلى مصفوفة
vectorizer = CountVectorizer()
train_vector = vectorizer.fit_transform(train.Message.fillna(''))  # استبدال NaN بسلسلة فارغة

# عرض المصفوفة
print(train_vector.toarray()) 


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [23]:
from sklearn.naive_bayes import MultinomialNB

# إنشاء نموذج Naive Bayes
model = MultinomialNB()
model.fit(train_vector, train.spam) 


MultinomialNB()

In [30]:
# تحويل بيانات الاختبار
test_vector = vectorizer.transform(test.Message.fillna(''))  # استبدال NaN بسلسلة فارغة

# عرض مصفوفة الاختبار
print(test_vector.toarray())


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [35]:
# اختبار عينة جديدة من الرسائل
emails = ['Congratulations! You have won a free ticket to the concert.']
emails_vector = vectorizer.transform(emails)
emails_vector

<1x7701 sparse matrix of type '<class 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [36]:
# التنبؤ بالفئة
predictions = model.predict(emails_vector)
print(predictions)

[1]
